export * from './origen.facade';
export * from './solicitante.facade';
export * from './espacio-academico.facade';
export * from './curso.facade';
export * from './horario.facade';
export * from './docente.facade';
export * from './plan-academico.facade';
export * from './detalle-horario.facade';
export * from './programacion-academica.facade';
