export interface Compensacion{
  idSecuencia:string,
  idMembresia:string ,
  descMembresia:string ,
  idServicio:string,
  descServicio:string,
  idOrigen:number,
  descOrigen:string,
  idClaseTransaccion:number,
  descClaseTransaccion:string,
  idCodigoTransaccion:number,
  descCodigoTransaccion:string,
  idCanal:number,
  descCanal:string,
  idInstitucionEmisora:number,
  descInstitucionEmisora:string,
  idInstitucionReceptora:number,
  descInstitucionReceptora:string,
  numeroTarjeta:string,
  bin:string,
  descBin:string,
  idMonedaCompensacion:number,
  descMonedaCompensacion:string,
  valorCompensacion:number,
  fechaTransaccion:Date,
  fechaProceso:Date,
  codigoRespuesta:string,
  descCodigoRespuesta:string,
  numeroTrace:string,
  codigoAutorizacion:string,
  referenciaIntercambio:string,
  nombreAdquirente:string,
  ciudadAdquirente:string,
  paisAdquirente:string,
  descPaisAdquirente:string,
  horaTransaccion:string,
  instFondosCargo:string,
  instFondosAbono:string,
  idTransaccion : number
}

export interface DetalleCompensacion extends Compensacion{
  idFacturacion:string,
  numeroTarjeta:string,
  numeroCuenta:string,
  idMonedaTransaccion:number,
  descMonedaTransaccion:string,
  valorTransaccion:number,
  fechaTransaccion:Date,
  fechaProceso:Date,
  fechaInterface:Date,
  fechaIncoming:Date,
  fechaSwitch:Date,
  fechaAfectacion:Date,
  codigoRespuesta:string,
  numeroTrace:string,
  codigoProcesamiento:string,
  idTerminal:string,
  binReceptor:string,
  descBinReceptor:string,
  idEstablecimientoLocal:number,
  referenciaIntercambio:string,
  referenciaTc:string,
  codigoUso:string,
  descCodigoUso:string,
  idPaisEmisor:string,
  descPaisEmisor:string,
  idRegionEmisor:string,
  descRegionEmisor:string,
  idPaisReceptor:string,
  descPaisReceptor:string,
  idRegionReceptor:string,
  descRegionReceptor:string,
  idTransaccionOriginal:string,
  descTransaccionOriginal:string,
  estadoAdquirente:string,
  terminalPos:string,
  modoEntradaPos:string,
  atributoReembolso:string,
  indCondicionEspecial:string,
  indAutorizacion:string,
  metodoIdThb:string,
  indCorreoTelefono:string,
  descIndCorreoTelefono:string,
  flagCompensacion:string,
  seleccionCuentaAtm:string,
  compensadoFondos:number,
  compensadoComisiones:number,
  comisionTarjetahabiente:number,
  comisionEstablecimiento:number
  comisionIntercambio:number,
  fondosCargo:number,
  fondosAbono:number,
  indicadorCompensacion:string,
  descIndicadorCompensacion:string,
  transaccionTipoC:number,
  horaTransaccion:string,
  glosaRegularizacion:string,
  porcentajeEstabLocal:number,
  indMonedaInter:string,
  posConditionCode:string,
  binAdquirenteSwitch:string,
  descBinAdquirenteSwitch:string,
  binRespuestaSwitch:string,
  descBinRespuestaSwitch:string,
  binEmisorSwitch:string,
  descBinEmisorSwitch:string,
  cargoSwitch:number,
  abonoSwitch:number,
  cuentaId1Switch:string,
  cuentaId2Switch:string,
  numeroCuotas:number,
  codigoRelacionador:string,
  cuotaAccesoAtm:number,
  codigoPct:string,
  codigoPlanCredito:string,
  codigoArticulo:string,
  indicadorPcas:string,
  descIndicadorPcas:string,
  origenArchivo:string,
  descOrigenArchivo:string,
  aplicaCuotaIsa:string,
  indTxnRecurrente:string,
  descTerminalPos:string,
  descModoEntradaPos:string,
  descMetodoIdThb:string,
  descFacturacion:string

  valorCompensacionFormatoMoneda:string,
  valorTransaccionFormatoMoneda:string,
  comisionTHBFormatoMoneda:string,
}
export interface ComisCompensacion{
  idSecuencia:string,
  fechaProceso: Date,
  idComision: number,
  descripcionComision: string,
  idCuentaCompensacion:number,
  descIdCuentaCompensacion:string,
  registroContable:string,
  descRegistroContable:string,
  valorComision: number,
  nivelTarifario:number,
  aplicaTarifaFlat: number,
  aplicaTarifaPorcentual: number,
  tarifaFlat: number,
  tarifaPorcentual: number,

  idMonedaTarifario:number,
  descMonedaTarifario:string,
  contadorTxn:number,
  aplicaIgv:number,
  igvAplicacionTarifa:number,
  aplicaGrupoBin:number,
  idGrupoBin:number,
  infTarifaEmisor:number,
  indicadorCompensacion:string,
  compensaComisiones:number,
  idMonedaCompensacion:number,
  descMonedaCompensacion:string,
  tipoCambioAplicado:number,
  descIndicadorCompensacion:string


  }
